### PR TITLE
Specify credentials for testing front50 GCS separate from Compute cre…

### PR DESCRIPTION
**Pull request by ewiseblatt**
@jtk54 When merging this we'll need to check jenkins configuration to pass in a --gcs_json_path.

### CODE REVIEW

**Comment by ewiseblatt** [comment]
I'm going to add the refactoring to remove primaryAccountName to this PR.

**Comment by ewiseblatt** [comment]
@jtk54 I'll do them as separate PRs. This is ready as is.

**Comment by ewiseblatt** [comment]
Changed the theme of this PR to removing the primaryAccountName afterall.

@lwander I removed references from experimental as well. Not sure why there are a lot of config files there, I didnt look at the details but those files are likely quite stale. Either we should discuss a different way to manage them or you should look into purging them.

**Comment by lwander** [comment]
You're right about the config files in experimental, but they'll be purged soon<sup>tm</sup>.

**Pull request merged**
