### PR TITLE
docs(contributing): Contributing.md doc links to spinnaker.io

### PR DESCRIPTION
**Pull request by louisjimenez**
Add contributing.md

### CODE REVIEW

**Comment by dorbin** [comment]
@bobcatfish

**Comment by louisjimenez** [comment]
Did some research and I found a simpler way to share these files across repos. If we create a new .github repo under the spinnaker org we can place the files there and they will serve as the default for any repos that do not already have them. @ttomsu are you able to add a new `.github` repo under the spinnaker org for sharing community health files? I don't have org permissions to do so but steps are [here](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization#creating-a-repository-for-default-files) or I'm happy to walk through it when you have a moment.

**Comment by bobcatfish** [comment]
>  If we create a new .github repo under the spinnaker org we can place the files there and they will serve as the default for any repos that do not already have them.

whoa that's cool! i had no idea you could do that :D

**Comment by bobcatfish** [comment]
one thing i want to add tho: i would guess that interacting with each project in the org will be slightly different (e.g. running kayenta would be different from running spinnaker) so eventually you might want to have unique DEVELOPMENT.md guides for each repo (or some unique content) 🙏

**Comment by dorbin** [comment]
That's a good point, @bobcatfish .
@demobox , currently the docs we have for development and contributing treat the whole spinnaker org the same. Do we want to account for different practices for Kayenta?

**Comment by plumpy** [comment]
Adding it to a .github repo just makes it the _default_ contributing guidelines. I think Kayenta is a significant outlier and that repo can have its own checked in separately. The rest of them are pretty much all part of Spinnaker.

(and nice job finding that, @louisjimenez!)

**Comment by louisjimenez** [comment]
One more quick note is that in the case of Development.md that file is not part of the set of Github's [supported file types](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization#supported-file-types) so it will need to be added to each repo. The code of conduct and contributing files are supported and can be added as defaults.

I am going to close this PR and instead work with someone who has ownership access to the Spinnaker Org to create the repo for default files.

**Comment by ttomsu** [comment]
.github repo created: https://github.com/spinnaker/.github

**Pull request closed without merging**
