### PR TITLE
Add install option for dependencies only -- no spinnaker services

### PR DESCRIPTION
**Pull request by ewiseblatt**
@dpeterka, @cfieber

### CODE REVIEW

**Comment by ewiseblatt** [comment]
I'll let you merge so you can have all the others ready at the same time.

**Comment by dpeterka** [comment]
Quiet install usually means no output, can we change the option name to something like "dependencies-only"?

**Comment by ewiseblatt** [comment]
@dpeterka PTAL

**Comment by duftler** [comment]
Not as part of this PR, but it would be nice to have a flag that just installs using the default settings derived from the metadata server (i.e. provider and region/zone), with no prompting. The way it is now, the only way to avoid prompts for user input is to pre-configure zero providers (and that flag is combined with the no-output behavior).

**Comment by dpeterka** [comment]
I have no iddues here

**Comment by duftler** [comment]
First I thought you said you have "no ideas here", then I realized it was "no issues here"...

**Comment by duftler** [comment]
LGTM.

**Pull request merged**
