### PR TITLE
Switch from deploying replication controllers to replica sets

### PR DESCRIPTION
**Pull request by lwander**
I also dropped the startup command in the deck image that's no longer necessary since deck now runs on apache.

### CODE REVIEW

**Comment by lwander** [comment]
@duftler @skim1420 @jtk54 PTAL

**Comment by skim1420** [comment]
Nice, thanks.

**Comment by dforrest88** [comment]
Are replication controllers still supported for auto-discovering applications deployed into the cluster via kubectl, or do they need to be deployed as replica sets in order to be picked up by Spinnaker? I've deployed a replication controller via kubectl to a cluster that my Spinnaker is connected to, and it doesn't appear to be loading into the Applications view properly. I'm wondering if I need to convert from Replication Controllers to Replica Sets.

**Comment by lwander** [comment]
It should still be picked up by Spinnaker - this commit just changes the default installation of Spinnaker into Kubernetes.

**Pull request merged**
