### PR TITLE
Check ownership of sensitive files.

### PR DESCRIPTION
**Pull request by ewiseblatt**
Fix for https://github.com/spinnaker/spinnaker/issues/949

@wgjohnson verify this satisfies your needs and expectations.
@duftler review

### CODE REVIEW

**Comment by duftler** [comment]
LGTM once @wgjohnson verifies the change.

**Comment by wgjohnson** [comment]
I'm using AWS AMI 'Spinnaker-Ubuntu-14.04-40' from Spinnaker.io. The fixed version seems a lot newer[1], and fails to start because of missing module "Configurator"[2]. How important is it that I personally test this?

Also, per new comments for #949, other local files can be expected to have sensitive information. If it isn't issue-creep, I would suggest verify_security() includes at least gate-local.yml, and possibly more (Sorry, I'm not familiar enough with Spinnaker to know which files are implied to have sensitive information). If it is creep, and you're okay with me not explicitly testing it, LGTM.


1 - 
```
ubuntu@ip-172-31-197-212:/opt/spinnaker$ wc -l bin/validate_configuration.*
  329 bin/validate_configuration.ewiseblatt:check_ownership.py
   19 bin/validate_configuration.sh
```

2 - 
```
ubuntu@ip-172-31-197-212:/opt/spinnaker/bin$ sudo ./validate_configuration.ewiseblatt\:check_ownership.py 
Traceback (most recent call last):
  File "./validate_configuration.ewiseblatt:check_ownership.py", line 22, in <module>
    from configurator import Configurator
ImportError: No module named configurator
```

**Comment by ewiseblatt** [comment]
The python file is intended to be used a s library in support of the bash
script, which sets the python path.

Checking -local files makes sense, though I dont know what passwords would
be in gate.
Normally clouddriver-local and spinnaker-local would be the main places.
Maybe igor.
What is the gate password for?

**Comment by wgjohnson** [comment]
Java keystore password per http://www.spinnaker.io/docs/securing-spinnaker

**Comment by ewiseblatt** [comment]
I'm not addessing the other -local files here because of potential unanticipated consequences before I leave on vacation. But will open an issue for it.

**Pull request merged**
