### PR TITLE
Proxy gate and rosco through Apache alongside deck

### PR DESCRIPTION
**Pull request by heph**
cc @vjames-bmc 

Configures Apache to proxy gate and rosco on the same <VirtualHost> as deck.

Adds instructions for setting custom deck.{baseUrl,gateUrl,bakeryUrl}

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
any @spinnaker/reviewers have feedback on this?

**Comment by ajordens** [comment]
Changes look sensible to me.

To clarify, what are we achieving by proxying `rosco`? Not required for normal operation but just like the convenience of being able to hit it's API directly?

**Comment by duftler** [comment]
Rosco is used in the Bakery Details Link in the OSS Bake Stage execution details. The link resolves to the packer logs.

**Comment by duftler** [comment]
LGTMA. @ewiseblatt any concerns with the unified config changes?

**Comment by ajordens** [comment]
Ahh of course it is Matt. Makes sense.

**Comment by ewiseblatt** [comment]
LGTM.

**Pull request merged**
