### PR TITLE
fix(approvers): update danielpeach  username

### PR DESCRIPTION
**Pull request by ethanfrogers**
dpeach is not @danielpeach username. also, since daniel isn't working on this team anymore, do we want to continue to allow approvals?

### CODE REVIEW

**Comment by ethanfrogers** [comment]
@lwander @skim1420

**Comment by skim1420** [comment]
This should go up to the TOC.

**Comment by lwander** [comment]
We haven't removed approvers/reviewers yet (AFAIK) for leaving a Spinnaker team. Let's add Dan's correct username for now, and decide on a more general policy later.

**Comment by lwander** [comment]
Oops, didn't refresh before posting that. Will take it up with the TOC

**Comment by ttomsu** [comment]
TOC approved.

**Pull request merged**
