### PR TITLE
refactor(release): Remove unused nebula code

### PR DESCRIPTION
**Pull request by lwander**
Removes all references to unused `nebula` & `nonebula` flags, as well as removes code to publish install script (which isn't referenced/validated against these releases anyhow).

This is done to make xenial support a bit easier in a coming PR.

### CODE REVIEW

**Comment by ewiseblatt** [comment]
I dont remember exactly offhand, but I recall wanting an option to bypass
nebula and it looks like this might be doing away with that. I dont really
do builds at the moment, but when I did, nebula is a pain to deal with as a
developer because it requires clean synced repos (i.e. you cannot build
changes you are working on because your repos arent properly tagged, etc).
If the change here does not prevent you from being able to just build your
current developer state then I cannot think of a problem with it.

Ideally nebula would be changed to be able to bypass some of its
restrictions, but that's a different issue.

**Comment by lwander** [comment]
Do any of us actually use it? The code is immortalized in version control, so removing it from HEAD doesn't make it irrecoverable.

**Comment by ewiseblatt** [comment]
Not at the moment, but seems fundamentally wrong to me to not be able to
perform informal builds.

**Comment by lwander** [comment]
Well I can't seem to get it to work, there isn't any documentation/description of how to use it, and as far as we know there isn't anyone actively using it. I'd like to extend these scripts to support more flavors of ubuntu, and this code makes that very difficult.

When you say informal, do you mean "without publishing to our proper bintray repo"? or "without publishing to any repo"? or something else?

**Comment by ewiseblatt** [comment]
Forget it. It seems there are more issues that crept in preventing
convenient informal builds.

**Pull request merged**
