### PR TITLE
Adds blank defaults, even when disabled

### PR DESCRIPTION
**Pull request by ttomsu**
Unresolvable ENV vars break /resolvedEnv endpoint, so I added blank string defaults.

@lwander @varikin PTAL

### CODE REVIEW

**Comment by lwander** [comment]
Having those colons break config: https://github.com/spinnaker/spinnaker/issues/1058

This should be fixed in /resolveEnv

**Comment by varikin** [comment]
Do you want the same in `default-spinnaker-local.yml`?

**Comment by varikin** [comment]
@lwander would `${ENV_VAR:''} be any different in regards to #1058?

**Comment by ttomsu** [comment]
Fixing in Kork. Closing this PR

**Pull request closed without merging**
