### PR TITLE
Fiat docker-compose config

### PR DESCRIPTION
**Pull request by gbougeard**
@spinnaker/reviewers @ttomsu  PTAL
linked to https://github.com/spinnaker/fiat/pull/79

### CODE REVIEW

**Comment by ttomsu** [comment]
LGTM. Leaving to @lwander for further review

**Comment by lwander** [comment]
LGTM2

**Comment by gbougeard** [comment]
Some links to fiat are maybe missing...

**Comment by ttomsu** [comment]
I'll merge this now, and we'll revisit when we need to add the links later

**Pull request merged**
