### PR TITLE
Configure notifications in Deck

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Configures the notifications displayed in the UI based on Echo's configuration.

@ewiseblatt PTAL - I'm guessing this will work as expected, but am not sure how to verify it...

### CODE REVIEW

**Comment by ewiseblatt** [comment]
I dont have deck tests, only for backend (REST) services.

One way you can test this is by running the spinnaker/runtime/reconfigure_spinnaker.sh script from your build directory, then looking at deck/settings.js (unfortunately, this will overwrite your deck/settings.js file as we've discussed before, so be sure you have a backup or a local commit you can restore).

If all goes well, the spring variable references should be resolved.
An easy way to do this is to simply grep for the reference, and filter our the commented templates
grep "\\$" settings.js | grep -v "// var"

When I run this command on what's already submitted in my client, it seems there is a bug here
var kubernetesDefaultNamespace = '${providers.kubernetes.primaryCredentials.namespace}';

@lwander either this is the wrong property, or you need to add a default to spinnaker.yml (and should also add it to default-spinnaker-local.yml for ease of user-configuration)

I'm going to modify the reconfigure_spinnaker.sh script to add this test in now that you've brought it up and I'm thinking about it.

LGTM otherwise.

**Comment by ewiseblatt** [comment]
I mistyped the command, appearently you need to double-escape the $.
 grep "\\$" settings.js | grep -v "// var"

**Comment by ewiseblatt** [comment]
Hmm, I didnt mistype it, github is interpreting it somehow. The grep command should be double-escaping the $ with two slashes.

**Comment by lwander** [comment]
Would 
` var kubernetesDefaultNamespace = '${providers.kubernetes.primaryCredentials.namespace:default}';` work? Not sure how the string interpolation works with javascript + spring

**Comment by ewiseblatt** [comment]
There is no interpolation with javascript. The mapping is done with our
script. Our script would do the substitution so this would work.

However, I do not think it would be desirable because it is a subtle
configuration that could easily go unnoticed.
It would be best to expose it in spinnaker-local.yml so that people can see
and know it is there and easily change it.
You can set the default in spinnaker.yml even if it is only to support the
deck settings (conceptually settings.js gets this configuration value from
spinnaker.yml even though it needs reconfigure_spinnaker.sh to achieve this)

**Comment by lwander** [comment]
Ah I see, submitted a PR https://github.com/spinnaker/spinnaker/pull/852

**Comment by anotherchrisberry** [comment]
@ewiseblatt Just to be sure before I push the button - this is okay to merge?

**Comment by ewiseblatt** [comment]
I pushed it for you (but did not create a release).

**Pull request merged**
