### PR TITLE
fix(tests): use xenial for bake and deploy test

### PR DESCRIPTION
**Pull request by plumpy**

### CODE REVIEW

**Comment by plumpy** [comment]
@spinnakerbot 🍒 ⛏ release-1.16.x
@spinnakerbot 🍒 ⛏ release-1.17.x

**Comment by plumpy** [comment]
@spinnakerbot 🍒 ⛏ 1.16
@spinnakerbot 🍒 ⛏ 1.17

**Comment by ttomsu** [comment]
You probably have to do them in two different messages

**Comment by plumpy** [comment]
@spinnakerbot cherry-pick 1.16

**Comment by plumpy** [comment]
@spinnakerbot cherry-pick 1.17

**Pull request merged**
