### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by sstrato**
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](http://spinnaker.io/online_docs/community/contributing_guidelines.html) and [On Collaborative Development](http://spinnaker.io/documentation/collab_dev.html).

When filling out a pull request, please consider the following:

* Provide a descriptive title for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days. 

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.
brew  cast changes the repo.

### CODE REVIEW

**Comment by lwander** [comment]
Can you describe what this PR does, and the motivation behind it?

**Comment by sstrato** [comment]
I've tried to install spinnaker in OS X  elcappitan  version.
Current How-to for installing 'brew-cast' is not working. So i updated document.

**Comment by lwander** [comment]
Have you verified this works for older versions of OSX?

**Comment by sstrato** [comment]
This link explains better   [homebrew-cask ](https://github.com/caskroom/homebrew-cask#important-december-2015-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system)

**Comment by lwander** [comment]
Cool, thanks for the link!

I don't own a mac to double check this works, could someone on @spinnaker/reviewers with a mac take a look?

**Pull request merged**
