### PR TITLE
Disable cassandra by default for echo.

### PR DESCRIPTION
**Pull request by duftler**
Disable Cassandra and enable in-memory by default for echo.

### CODE REVIEW

**Comment by duftler** [comment]
@lwander or @danielpeach please review.

**Comment by danielpeach** [comment]
LGTM

**Comment by ewiseblatt** [comment]
this has production implications.
I'm not sure you want to do that.

**Comment by duftler** [comment]
We discussed this offline. The changes only affect the default behavior of echo and not of front50. Our nightly images have also been produced with these settings in effect for some time already.

**Comment by ewiseblatt** [comment]
The nightly images use InstallSpinnaker which runs
pylib/spinnaker/change_cassandra.sh to modify spinnaker.yml as if these
changes had been made.

**Pull request merged**
